"""empty message

Revision ID: 589a67ffb68
Revises: 507b4397990
Create Date: 2015-02-15 14:07:55.701540

"""

# revision identifiers, used by Alembic.
revision = '589a67ffb68'
down_revision = '507b4397990'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
