"""empty message

Revision ID: 26d1eae9445
Revises: None
Create Date: 2015-02-14 18:21:25.728917

"""

# revision identifiers, used by Alembic.
revision = '26d1eae9445'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
