"""empty message

Revision ID: 507b4397990
Revises: 26d1eae9445
Create Date: 2015-02-14 18:25:03.539375

"""

# revision identifiers, used by Alembic.
revision = '507b4397990'
down_revision = '26d1eae9445'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
